### PR TITLE
Bumping netty version from 3.9.2 to 4.0.21. 

### PR DESCRIPTION
**Pull request by mxk1235**
Code changes are only enough to get it to compile, and everything was done with the help of the following resources: 

http://netty.io/wiki/new-and-noteworthy-in-4.0.html#wiki-h3-25  
http://netty.io/4.0/api/index.html  
http://netty.io/3.9/api/index.html   

Tests currently fail, as i suspect the server does not handle any requests, i.e. perhaps the handlers are never invoked.  please consider this a draft version of the pull request and if anything jumps out at you as obviously wrong, i will gladly fix it.

### CODE REVIEW

**Comment by flowersinthesand** [comment]
@mxk1235 By any chance, do you still have that git repository? I can access your work through GitHub interface but can't checkout it, `git checkout e5007f287bf778a981f6eb79c4a89e78f4a0393f`.

**Comment by mxk1235** [comment]
i do have it locally.  if you'd like, i could post a patch, which you could apply on top of ea8b4fcb99956933031663f42005e3f3ef6237dc.  unless you prefer to resurrect it in a different way.  let me know.

**Comment by mxk1235** [comment]
you can grab it here https://github.com/mxk1235/nettosphere/tree/netty4  

fair warning i am probably going to nuke it after a few weeks.

**Comment by flowersinthesand** [comment]
Thanks! I forked your repository. I'll keep you posted on my work. https://github.com/flowersinthesand/nettosphere/commits/netty4

**Comment by ahmedaswai** [comment]
Is the migration finished because we are currently using netty 4

**Comment by flowersinthesand** [comment]
As for me, I couldn't have time to do that.

**Comment by mxk1235** [comment]
this direction ultimately was not a good approach for us.  Resteasy-netty4 with raw netty4 sockets was much simpler.

**Pull request closed without merging**
